# Spring Boot Application Name
spring.application.name=user_onboarding
server.port=8081


# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/htdsdb
spring.data.mongodb.database=htdsdb

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#  Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=htds-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#  Logging Levels
logging.level.root=INFO
logging.level.com.anshika_project=DEBUG



